# 前端工程启动的时候，是使用npm start | npm start
# 前端工程启动命令start是一个批处理命令，启动了两个服务。 npm run serve 和 mock
# 1、 Vue的前端应用，占用端口80。
# 2、 Mock的静态测试服务，占用4006端口。

server:
  post: 4006
spring:
  application:
    name: livegoods-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # 开启当前项目服务注册与发现功能
          lower-case-service-id: true # 把服务名转换为小写，Eureka 中默认都是 大写
      routes:
        - id: banner  # unique identity
          uri: lb://LIVEGOODS-BANNER  # lb:loadBalance EUREKA-CLIENT 代理项目的名
          predicates:
            - Path=/banner  # path rule
        - id: topProduct
          uri: lb://LIVEGOODS-TOPPRODUCT
          predicates:
            - Path=/topProduct
            - Query=city # query must contain city e.g. http://localhost:4006/hotProduct?city=北京
        - id: recommendation
          uri: lb://LIVEGOODS-RECOMMENDATION
          predicates:
            - Path=/recommendation
            - Query=city
        - id: search
          uri: lb://LIVEGOODS-SEARCH
          predicates:
            - Path:/search
            - Query=city
            - Query=page
            - Query=content
        - id: details
          uri: lb://LIVEGOODS-DETAILS
          predicates:
            - Path=/details
            - Query=id
        - id: comment
          uri: lb://LIVEGOODS-COMMENT
          predicate:
            - Path=/comment
            - Query=id
            - Query=page
        - id: buytime
          uri: lb://LIVEGOODS-BUYACTION
          predicates:
            - Path=/buytime
            - Query=id
        - id: sendVC
          uri: lb://LIVEGOODS-LOGIN
          predicates:
            - Path=/sendyzm
        - id: login
          uri: lb://LIVEGOODS-LOGIN
          predicates:
            - Path=/login
        - id: buyaction
          uri: lb://LIVEGOODS-BUYACTION
          predicates:
            - Path=/buyaction
        - id: order
          uri: lb://LIVEGOODS-ORDER
          predicates:
            - Path=/order
            - Query=user
        - id: feelback
          uri: lb://LIVEGOODS-COMMENT
          predicates:
            - Path=/feelback

eureka:
  client:
    service-url:
      defaultZone: http://192.168.119.7:8761/eureka/