livegoods:
  search:
    init:
      enabled: true # whether to create index and mapping when init

spring:
  profiles:
    active: mongodb,bannerNginx
  application:
    name: livegoods-search
  elasticsearch:
    rest:
      uris: http://192.168.119.11:9200

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://192.168.119.8:8761/eureka/
  instance:
    prefer-ip-address: true