server:
  port: 9008

spring:
  application:
    name: livegoods-buyaction
  profiles:
    active: buyQueue,itemCacheName,redis,rabbit

eureka:
  client:
    service-url:
      defaultZone: http://192.168.119.8:8761/eureka/
  instance:
    prefer-ip-address: true